name: QA Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests: 
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v6

      - name: Build Docker image
        working-directory: ./saucedemo
        run: docker build -t qa-saucedemo .

      - name: Run tests
        run: docker run --rm --ipc=host qa-saucedemo